### ISSUE TITLE
NdNorms ChunkIdentifier not in header.

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-rust#101]
I'm implementing stand-alone reading + writing for the different chunks in my Python fork and it seems like we never added the `NdNorms' chunk identifier to the list in the header. 

I think it's not a breaking change if we add the identifier to the header. Inside `finalfusion`, we don't use the chunk identifiers for storage, vocab and norms in any way, iirc.

**Comment by danieldk** [comment]
Fixed by #102 .
