### ISSUE TITLE
Documentation outdated in 'io.rs'?

### ISSUE THREAD

**Issue by NianhengWu** [finalfusion/finalfusion-rust#109]
[Here](https://github.com/finalfusion/finalfusion-rust/blob/10f9242fc1a559a2946cc16d3665db6d4260d5ec/src/io.rs#L147), if I understand it correctly, is outdated right? Since we have ```Embeddings<_, MmapQuantizedArray>``` already.

**Comment by danieldk** [comment]
Good catch! Could you do a PR?
