### ISSUE TITLE
Zero-allocation lookups

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#110]
Add a method `Embedings::embedding_into` that constructs the embedding in-place in an `ArrayViewMut1`. Obviously, this would be a copy for a known word, but for unknown words, this avoids an allocation in case one already has memory allocated (e.g. in downstream software where you allocate memory for embeddings for all words in a sentence).

**Comment by sebpuetz** [comment]
Batched lookups would be nice, too. Straight forward implementations would be restricted to non-ragged inputs. In combination with `embedding_into` that would save even more allocations.

1. verify non-raggedness
2. allocate `Array*` with correct shape
3. 
~~~Rust
for (row, query) in array.genrows_mut().zip(flattened_query.into_iter()) {
    self.embedding_into(row, query);
}
~~~

But I guess your idea is to implement this functionality in downstream applications as required?

**Comment by danieldk** [comment]
But batched lookups are easy to implement client-side, especially with `embedding_into`. But you can not do a no-alloc lookup without help of the proposed method.

**Comment by danieldk** [comment]
I'll take this one, shouldn't take more than a few minutes to implement.
