### ISSUE TITLE
The analogy method should return which words could not be looked up

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#12]
Proposed solution: change `analogy` to return a `Result<..., [bool; 3]>`.

See also: finalfusion/finalfusion-utils#8

**Comment by danieldk** [comment]
Unless you already have something, I can take this one, I'd like to push out a new finalfusion-python release soon-ish.

**Comment by sebpuetz** [comment]
I haven't put any work into this

**Comment by NianhengWu** [comment]
I'm almost finished, but I just saw you already have a PR

**Comment by danieldk** [comment]
Fixed in #14.

@NianhengWu let me know if you have any improvements.
