### ISSUE TITLE
Vocab should be a supertrait of SubwordVocab

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#123]
Every `SubwordVocab` is also a `Vocab`. This has the benefit that when you have a `dyn SubwordVocab` that the `Vocab` methods are also available.

This should by a safe API change (since it only adds methods accessible through `SubwordVocab`).

**Comment by sebpuetz** [comment]
But `SubwordVocab` is not a trait, it's a struct and it implements `Vocab`. The methods should be available on `SubwordVocab<I>` if `Vocab` is imported and `I: Indexer` since we have:
```Rust
impl<I> Vocab for SubwordVocab<I>
where
    I: Indexer,
```

Or am I misunderstanding something?
