### ISSUE TITLE
How to use Ngrams to find words not in dictionary

### ISSUE THREAD

**Issue by jguhlin** [finalfusion/finalfusion-rust#128]
Hey again. So the API is confusing for me here, but when I try to get an embedding and it is not found, what is the proper way of using the Ngram module to get the embedding? Is there a pre-built fn to do it or an example somewhere in the test code?

``Rust
    #[inline]
    pub fn get_embedding(&self, kmer: &str) -> Embedding {
           match self.embeddings.embedding_with_norm(&kmer) {
            Some(x) => x.embedding.into_owned(),
            None    => panic!("Unable to get embeddings for {}", kmer)
            // Probably have to use the ngrams module to get indices, and then average...
        }
    }
``

I'm using an alternative vocab, but it is working from the NGram bones (with very few changes)
``
impl From<KmerVocab<NGramConfig, ExplicitIndexer>> for VocabWrap {
    fn from(v: KmerVocab<NGramConfig, ExplicitIndexer>) -> Self {
``

Thanks

**Comment by sebpuetz** [comment]
Hi,
`Embeddings.embedding` gets the indices and averages the known embeddings already, no need to do that manually. The method returns `None` if the model does not know any parts of the input, i.e., none of the ngrams of the input `kmer` are in its vocabulary. In my experiments with explicit ngram vocabs, I usually used a randomly initialized vector to represent unknown words. Another option is to take the average of the known words.
Best

**Comment by danieldk** [comment]
@jguhlin did @sebpuetz's answer resolve your question?
