### ISSUE TITLE
compiling to wasm

### ISSUE THREAD

**Issue by drbh** [finalfusion/finalfusion-rust#129]
This is an awesome project sadly I cannot compile it to wasm for native browser use because of the `memmap` dep?

This seems to be used in
src/chunks/storage/array.rs:8:5  
src/chunks/storage/quantized.rs:6:5  

is there a way to remove memmap? or replace it with something that can target wasm? 

Thanks

**Comment by danieldk** [comment]
I think the most straightforward fix would be to feature-gate the memory-mapped embeddings. We would accept a PR with such a change, as long as the feature is enabled by default. Memory mapping support is actually already disabled for big-endian platforms, so it would be straightforward to do that.

**Comment by sebpuetz** [comment]
I found some time to look into this, I can build the crate with `--target wasm32-unknown-unknown --no-default-features` on branch `memmap-optional`. I also created a PR at #130, hope this solves your issue.
