### ISSUE TITLE
Release Explicit Conversions?

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-rust#161]
Not sure whether this should go as a dot-release or as a new version...

**Comment by danieldk** [comment]
Do we have any API changes compared to the last dot release?

We probably need something in `finalfusion-utils` to use this API as well, right?

**Comment by sebpuetz** [comment]
I just opened a (draft) PR in utils. Changes were a bump of `OrderedFloat` to 2.0 and addition of a new trait. Also a minor API-breaking change with the `ExplicitIndexer` now returning the mapping:

```Rust
    pub fn new_with_indices(
        ngram_tuples: impl IntoIterator<Item = (String, u64)>,
    ) -> (Self, HashMap<u64, usize>)
```

used to be

```Rust
    pub fn new_with_indices(
        ngram_tuples: impl IntoIterator<Item = (String, u64)>,
    ) -> (Self)
```

**Comment by danieldk** [comment]
We expose ordered-float in the public API (we should probable change this), so we need a semver  bump. I’ll do that on Monday.
