### ISSUE TITLE
Support for phrase embeddings

### ISSUE THREAD

**Issue by sachaarbonel** [finalfusion/finalfusion-rust#166]
Hi @danieldk thank's for this great library, can you guide me through the steps to include support for sentence embeddings using [sentence-transformer](https://github.com/google/sentencepiece)? Which traits should I use? I am specially interested in storing embeddings for similarity queries on phrases

**Comment by danieldk** [comment]
I might misunderstand your goal, however I think that finalfusion is not a good fit. (Pretrained) transformers provide contextual word representations. The API would require that you give a full sentence, and the library should give the contextual representation for every word in the sentence (or one particular word). However, the finalfusion API can only give an embeddings for tokens without their sentential context. If you are looking for transformer-based representations in Rust, you are better off with one of the following crates:

https://github.com/guillaume-be/rust-bert
https://github.com/stickeritis/sticker-transformers/
