### ISSUE TITLE
Relicensing to MIT or Apache License version 2.0

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#195]
finalfusion-rust is currently licensed under the following licenses (user's choice):

* Apache License Version 2.0
* Blue Oak Model License Version 1.0.0

We are trying to relicense the finalfusion ecosystem to something that is more canonical for the Rust ecosystem, namely (user's choice):

* Apache License Version 2.0
* MIT License

I, @sebpuetz, and SfS ISCL have agreed with relicensing all finalfusion projects in this way. However, finalfusion-rust has two additional contributors:

* @RealNicolasBourbaki
* @djc 

If you are ok with this relicensing, could you please reply to this issue confirming this? Thanks a lot!

**Comment by djc** [comment]
Happy to relicense my changes as requested!

**Comment by RealNicolasBourbaki** [comment]
I confirm as well :)

**Comment by danieldk** [comment]
Thanks a lot for the quick confirmations!
