### ISSUE TITLE
norms API

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#3]
I have the norms layer mostly done, but I was thinking about what the API should look like:

1. Provide a separate method `fn norm(&self, word: &str) -> Option<f32>`. Benefit: no cluttering of `embedding`'s signature. Most people will just want an embedding. Downside: more expensive if someone wants the embedding and the original norm, especially with subword units.

2. Extend the return type of `embedding` to `Option<(CowArray1<f32>, f32)>`, where embedding and norm are returned as a tuple. Advantage: faster than (1), disadvantage: tuple.

3. Extend the return type of `embedding` to `Option<Embedding>` where `Embedding` is a type that holds the `CowArray1` and the norm. Provide two getters: `embedding`/`norm`. Advantage: faster than (1), clearer than (2). Disadvantages: double wrapping of the actual vector (`Embedding` -> `CowArray`); getting the embedding is ugly (`embeds.embedding("blah").embedding()`); the `embedding` getter returns a reference, `&CowArray1` is not a very useful type in case the array is owned.

4. (2), but make this a separate method `fn embedding_with_norm(&self, word: &str) -> Option<(CowArray1<f32>, f32)>`.

Any opinions @sebpuetz ?

**Comment by sebpuetz** [comment]
4., the other solutions make some kind of compromise and having the additional method doesn't really hurt anything.
