### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#33]
@sebpuetz @NianhengWu 

We have accumulated quite some changes since June:

* fastText support
* The possibility to get n-grams + subword indices.
* Similarity queries for embeddings.
* Library-specific error types.
* Report of missing words in analogy queries.

Maybe it's time to do a new release branch of `finalfusion-rust` and `finalfusion-utils`? Are there any small changes we need to get in before? The primary thing on top of my head is a unit test using toy fastText embeddings.

**Comment by sebpuetz** [comment]
Also, the similarity queries for vectors were added. I don't have anything else in mind that should be added

**Comment by danieldk** [comment]
Released!
