### ISSUE TITLE
Adding a method for ngram -> idx mappings

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-rust#6]
I was wondering if there are reasons against exposing a method to get tuples of `(ngram, idx)` for both in vocabulary and out of vocabulary words.

Could be nice to inspect similarity of the subword vectors through the python module. Although, we probably can't get all components that make up in vocab words because we precompute theri representations.

**Comment by danieldk** [comment]
Thanks @NianhengWu for adding this!

I guess the next step would be: refactor the existing `subword_indices` method and exposing these methods in Python.

**Comment by danieldk** [comment]
Oh and maybe you could do a PR to append yourself to the list in `CONTRIBUTORS`?
