### ISSUE TITLE
Update README with examples

### ISSUE THREAD

**Issue by sebpuetz** [finalfusion/finalfusion-rust#63]
Some code snippets could be nice. Also, a synopsis of what you can do with the crate.

The README also states, that the crate is new and the API will change, while the API might still change, I think we're approaching somewhat stable levels in terms of public API.

**Comment by danieldk** [comment]
> Some code snippets could be nice.

Any code snippets should go in the rustdoc, we get automatic tests, ensuring that the snippets are not outdated. Of course, the readme could contain a link to the examples section of the crate main page.

> Also, a synopsis of what you can do with the crate. The README also states, that the crate is new and the API will change, while the API might still change, I think we're approaching somewhat stable levels in terms of public API.

I agree with both points.
