### ISSUE TITLE
Add an empirical comparison between array types

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#65]
Compare disk/memory use and speed of and add this to the README, to give people an idea of the trade-offs:

* Array
* Memory-mapped array
* Quantized array
* Memory-mapped quantized array.

I have already done parts of this, so I can take this one.

**Comment by sebpuetz** [comment]
I think that's a good idea. In the future we could also add a comparison between ngram and bucket indexing. I was planning to do this a few months ago but forgot about it. I'd add that once we have merged support for that vocabulary type both here and in `finalfrontier`.
