### ISSUE TITLE
Increase crates.io bus factor

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#7]
@sebpuetz @twuebi

Same as with PyPI, I think it would also be good to have additional owners on crates.io for the finalfusion crates and finalfrontier. Let me know your username (I think it's the same as the GitHub handle, but you probably have to log on once to create it on crates.io).

**Comment by twuebi** [comment]
Is the same as for GitHub, twuebi.

**Comment by sebpuetz** [comment]
I have a crates.io handle, should be my git name, too.
