### ISSUE TITLE
Fail CI upon benchmark failure

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#71]
This is a trivial change, but should go in a separate PR.

**Comment by sebpuetz** [comment]
I.e., move the benches to the `ci-script` instead of `after-success`?

**Comment by danieldk** [comment]
I don't like that semantically. It's really not part of the main build. Also, it relies on network, which tends to fail every once in a while on Travis CI. But it would be nice to get notified somehow if this fails.

I'll look into this a bit deeper, I think this could perhaps be solved by jointly also reporting the bench results on some page or in the PR request. Because now you have to dig in the CI results to see regressions.

**Comment by danieldk** [comment]
Fixed in #75.
