### ISSUE TITLE
Split Similarity trait

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#78]
For analogies, we have `Analogy` and `AnalogyBy`. However `Similarity` has both `similarity` and `similarity_by` methods.

**Comment by NianhengWu** [comment]
I guess I can do it if no one is currently on it

**Comment by danieldk** [comment]
That would be great! :+1:

**Comment by danieldk** [comment]
@NianhengWu thanks for fixing this!
