### ISSUE TITLE
Properly handle memory mapped storage on big-endian platforms

### ISSUE THREAD

**Issue by danieldk** [finalfusion/finalfusion-rust#99]

**Comment by danieldk** [comment]
This is a fun exercise, we had a lot of implicit endianness assumptions. I knew about memory mapping, but it turns out that bucket indexing also breaks. I have most issues fixed now and will do a PR soon-ish.

**Comment by sebpuetz** [comment]
What kind of platforms do we need to provide this for? Is the idea to just cover all targets supported by Rust? 

I'd expect that the vast majority of possible users is on AMD64 platforms...

**Comment by danieldk** [comment]
> What kind of platforms do we need to provide this for? Is the idea to just cover all targets supported by Rust?

ARM is popular and is bi-endian (can run in big and little endian). The other reason on to shake out unwarranted assumptions in the code. Portable code generally has fewer bugs.

**Comment by danieldk** [comment]
About platforms in general - I should dig out my Raspberry Pi 3 (AArch64) and see how well mmap'ed and quantized embeddings work (regular embeddings with subwords are obviously too large). Same for finalfusion + sticker.

**Comment by danieldk** [comment]
Fixed by #103 .
